version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
deploy: off

skip_tags: true
image:
 - Visual Studio 2017
 - Ubuntu
 language: csharp
mono: 5.4.0
dotnet: 2.2.1
os:
  - linux
  - osx
sudo: false
dist: trusty
osx_image: xcode9.1

clone_folder: c:\project\Hzexe.QQMusic
build_script:
  - cmd: dotnet publish /p:NativeLib=Shared -r win-x64 -c release QQMusic_Native_Library
artifacts:
 - path: ./QQMusic_Native_Library/bin/release
   name: Hzexe.QQMusic_release_win-x64

addons:
  apt:
    sources:
    packages:

for:
-
  matrix:
    only:
      - image: Ubuntu
  init:
    - sh: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && apt install -y clang-3.9
    - sh: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && apt install -y clang-3.9
  clone_folder: /home/appveyor/projects/
  build_script:
    - sh: dotnet publish /p:NativeLib=Shared -r linux-x64 -c release QQMusic_Native_Library
  artifacts:
    - path: ./QQMusic_Native_Library/bin/release
      name: Hzexe.QQMusic_release_linux-x64

